name = "pigiot-net"
compatibility_date = "2026-03-17"
send_metrics = false

[[routes]]
pattern = "pigiot.net"
custom_domain = true

[assets]
directory = "./target/dx/pigiot-net/release/web/public"
not_found_handling = "single-page-application"

[build]
command = "bunx @tailwindcss/cli -i ./assets/tailwind.css -o ./assets/styling/main.css -m && dx build --web --ssg --release --debug-symbols=false"
watch_dir = ["./src"]
